
// OPTIMIZED SERVER_CONSTANTS.ts
export const SERVER_CONSTANTS = {
  ENCODER_BUFFER_SIZE: 256 * 1024,
  TICK_RATE: 30, // Keep at 30Hz for now
  GRID_REBUILD_EVERY: 10, // ⚠️ CHANGED: Rebuild less frequently (was 2)
  AOI_LENGTH_NORMALIZATION: 2000,
  FOOD_AOI_SCALE: 1.1,
  MIN_FOOD_COUNT: 200,
  INITIAL_FOOD_COUNT: 500,
  PLAYER_SPAWN_RANGE: 1000,
  FOOD_SPAWN_NEAR_PLAYER_RANGE: 1000,
  FOOD_SPAWN_NO_PLAYER_RANGE: 10000,
  FOOD_ID_LENGTH: 9,
  SKIN_COUNT: 6,
  DISCONNECT_FOOD_FRACTION: 0.4,
  DISCONNECT_FOOD_DISTANCE_MIN: 50,
  DISCONNECT_FOOD_DISTANCE_MAX: 150,
  DISCONNECT_FOOD_VALUE: 1,

  ARENA_TIER_RADII: [0, 2000, 4000, 7000, 10000],
  ARENA_TIER1_MASS_MAX: 5000,
  ARENA_TIER2_MASS_MAX: 15000,
  ARENA_TIER3_MASS_MAX: 40000,
  ARENA_EDGE_START_RATIO: 0.9,
  ARENA_EDGE_SPEED_FACTOR: 0.85,
  ARENA_EDGE_PULL: 0.03,
  ARENA_CENTER_ZONE_RATIO: 0.4,
  ARENA_CENTER_SPAWN_WEIGHT: 2.5,
  FOOD_DENSITY: 0.00015,
  ARENA_MAX_FOOD: 3000, // ⚠️ REDUCED: Was 5000
  FOOD_SPAWN_MAX_PER_TICK: 50, // ⚠️ REDUCED: Was 150

  SNAKE_COLLISION_MAX_SEGMENTS: 80,

  // Larger snake segments
  SNAKE_MIN_SEGMENTS: 15,
  SNAKE_INITIAL_SEGMENTS: 15,
  SNAKE_INITIAL_COLLISION_SEGMENTS: 8,
  SNAKE_COLLISION_SEGMENT_SPACING_MULTIPLIER: 2,

  SNAKE_CONTROL_POINT_INTERVAL: 10,
  SNAKE_MAX_CONTROL_POINTS: 50,
  SNAKE_SIMPLIFICATION_INTERVAL_MS: 100,
  SNAKE_HEAD_HISTORY_MAX: 100,

  SNAKE_BOUNDING_SIZE_FACTOR_MAX: 2,
  SNAKE_BOUNDING_SIZE_FACTOR_DIVISOR: 500,

  // Better curves for larger snakes
  SNAKE_SIMPLIFIED_SEGMENTS_MIN: 4,
  SNAKE_SIMPLIFIED_SEGMENTS_MAX: 30,
  SNAKE_SIMPLIFIED_SEGMENTS_DIVISOR: 40,
  SNAKE_TAIL_RADIUS_FACTOR: 0.9,

  // Adjusted sync for larger snakes
  SNAKE_CLIENT_SYNC_MAX_SEGMENTS: 50,
  SNAKE_CLIENT_SYNC_MIN_SEGMENTS: 4,
  SNAKE_CLIENT_SYNC_SMALL_THRESHOLD: 80,
  SNAKE_CLIENT_SYNC_DIVISOR: 50,
  SNAKE_CLIENT_SYNC_ALWAYS_BELOW: 80,
  SNAKE_CLIENT_SYNC_EVERY_N: 10,

  SNAKE_LOD_HALF_DETAIL_DISTANCE: 2000,
  SNAKE_LOD_HALF_DETAIL_STEP: 2,
} as const;